### ISSUE TITLE
Formal descriptors for HOCON configuration

### ISSUE THREAD

**Issue by Horusiath** [akka/akka-meta#11]
The idea/proposal is to create a common descriptor format, which could be used to define a shape of the HOCON configuration. This way we could support things like IntelliSense, compile-time verification of any typo's or invalid types of the key/value pairs defined by end users.

**Comment by ktoso** [comment]
Fun idea, however this would be better discussed in http://typesafehub/config I think?
Technically speaking, we do have such a tool that checks if you made a typo etc, it's the config checker and is an commercial addon for Akka (in the Lightbend platform), I don't think in Akka itself there is much to be specced here to be honest–would you agree to close this ticket (esp. due to inactivity).
