### ISSUE TITLE
HOCON Strings

### ISSUE THREAD

**Issue by rogeralsing** [akka/akka-meta#2]
This is a crosspost from the developer list:

According to the HOCON Spec, and JSON Spec, only double quotes " are supported for quoted strings.
We on the .NET side of things have seen this beeing brought up a few times now.
That is, people beleive that single quotes are allowed.
e.g 

`loggers = ['F.Q.N, Assembly']`

Which is parsed as: 'F.Q.N,
As it is treated as an unquoted hocon string which ends after the ","

Does the JVM HOCON Parser allow this even though it is not mentioned in the spec?

And if not, would it be OK to add support for this?

I do realize that this would be a breaking change if people already use single quotes as chars in an unquoted hocon string.
But not treating single quotes as strings seems to be confusing for most people. at least our users :)

**Comment by viktorklang** [comment]
s/most people/some people with unafounded expectations due to haven't read the documentation

;)

**Comment by rkuhn** [comment]
The problem with doing this just because “people” believe that that’s how it is and getting hurt is that all the others who did read the docs will potentially face broken config files afterwards: we cannot just change the meaning of a ' character. But that is just my non-authoritative opinion, HOCON is defined and maintained over at https://github.com/typesafehub/config—and for this reason (and no other) do I close this issue.
