### ISSUE TITLE
Virtual actors/endpoints

### ISSUE THREAD

**Issue by Horusiath** [akka/akka-meta#3]
I want to continue the talk about virtual endpoints (name invented by Roger Alsing, since virtual actors may be a missleading). The whole talk started at akkadotnet/akka.net#756 and I think, we all (both JVM and .NET akka developers) should talk about this.

In short: virtual actors (as called by Orleans and Orbit frameworks) are not bound to any concrete instance or resource. From logical perspective, they are eternal. Virtual actor doesn't have an explicitly managed lifecycle and in case of failure i.e. crash of the server executing it, it's simply respawned on another node. Since it always exists, it's always addressable and responsive.

cc @rkuhn @rogeralsing

**Comment by rkuhn** [comment]
short notice: thanks for opening this issue, you are not ignored, but when I answer I want to have assembled all the relevant information first

**Comment by jthelin** [comment]
@rkurn -- When looking at the Project Orleans docs, you might want to compare its goals and features against your own http://www.ReactiveManifesto.org list because there is high correlation between them both.

**Comment by rkuhn** [comment]
After studying the Orleans Technical Report I created the comparison #8, I propose that we keep discussion about understanding the difference in nature between Orleans and Akka to that ticket so that the result can be a document that we persist.

On the topic of whether we might want to replicate elastic objects (which is my current proposal for naming the Orleans abstraction) in Akka / Akka.NET we might want to wait until our understanding is complete.

/cc @sergeybykov

**Comment by ktoso** [comment]
Seems to me like this was discussed in depth in #8, so closing this ticket.
Reopen if necessary.
