### ISSUE TITLE
Distribute Typed Akka Separately

### ISSUE THREAD

**Issue by sirinath** [akka/akka-meta#6]
Can this be distributed as a separate artifact. If you want to switch to typed Akka and do not care much for the untyped case. Also other artifacts need to be broken into typed and untyped jars.

(Maybe too early to comment on this improve documentation)

**Comment by ktoso** [comment]
Akka-Typed depends on Akka-Actor currently – so no, this is not possible during the experimental phase of akka-typed. Once it matures and we decide to make it a supported module we can revisit this (if it would be able to be implemented directly instead of "on-top-of-akka-actor").

Hope this helps!

**Comment by sirinath** [comment]
Wondering if you can break the dependency and make it independent by 2.4 RC1?

**Comment by ktoso** [comment]
It's not just a simple "break dependency", it would mean we have to reimplement how actors are implemented independently of akka-actor (which took years to polish) :-)

Akka-Typed will be experimental in 2.4.x.

**Comment by rkuhn** [comment]
There remains a lot to be done for Akka Typed, we currently only have the Scala side of an API, everything beneath the surface will eventually need to be reworked in order to benefit from the deeper improvements. This process will take years, it is a humongous task.

Again, this discussion and concern is specific to akka/akka, not a generic high-level conceptual question.
